apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template: 
    metadata: # Dictionary
      name: myapp-pod
      labels: # Dictionary 
        app: myapp       
    spec:
      containers: # List
        - name: myapp-container
          image: nginxinc/nginx
          ports:
            - containerPort: 8080


    