apiVersion: v1
kind: Service
metadata:
  name: replicaset-nodeport-service
spec:
  type: NodePort 
  selector: 
    app: myapp
  ports: 
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 31232
    