apiVersion: v1
kind: Service
metadata:
  name: myapp-pod-nodeport-service 
spec:
  type: NodePort 
  selector:
    app: myapp 
  ports: 
    - name: http
      port: 8080 # Service Port
      targetPort: 8080 # Container Port
      nodePort: 8080 # NodePort